### PR TITLE
Implement HTTP-network-or-cache Fetch

### PR DESCRIPTION
**Pull request by nikkisquared**
I'm working on implementing HTTP-network-or-cache Fetch[1], and I've just finished my first draft going over it. I know the code won't build yet, partly since there's implementation gaps for dependencies I need to make still, but I'd like feedback on my logic, how well I'm following the spec and translating it into Rust code.

[1] https://fetch.spec.whatwg.org/#http-network-or-cache-fetch

[Review on Reviewable](https://reviewable.io/reviews/jdm/fetch/2)

### CODE REVIEW

**Comment by jdm** [comment]
Good work! I've left some comments on ways that we can flesh out some missing steps in ways that are still meaningful to the reader, even if they're still just stubs in the current implementation. We should also get this compiling, as there's some type confusion related to Option values in particular that the compiler will make clear.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[src/fetch/request.rs, line 478 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5poTrFUwPUfjdLvYgB:-K5poTrFUwPUfjdLvYgC:-1058337754) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L478)):*
Note: in order to do this, `http_network_or_cache_fetch` will have to change from being a method on `Request` to being a standalone function that takes a `request: Rc<Request>` argument. I think this is a change we should make regardless for all of these methods.

---

*[src/fetch/request.rs, line 483 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5popNYwlpntyoWtXiz:-K5popNYwlpntyoWtXj-:1464655710) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L483)):*
This doesn't exactly work right now, since `httpRequest` ends up scoped to the two branches of this if/else block. This is actually kind of weird to support in the current setup (without the `Rc` changes mentioned earlier), since we'll basically need this:
```rust
let mut self_copy = self.clone();
let httpRequest = if request_has_no_window ... {
    self
} else {
    &mut self_copy
};
```

---

*[src/fetch/request.rs, line 496 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5ppMmYr0Z-HrwH-PEq:-K5ppMmYr0Z-HrwH-PEr:1649585487) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L496)):*
body.len()

---

*[src/fetch/request.rs, line 501 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5ppRmGpy1Wfp-PWwZi:-K5ppRmGpy1Wfp-PWwZj:-734410686) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L501)):*
if let Some(content_length_value) = content_length_value {

---

*[src/fetch/request.rs, line 509 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5ppkuoc1l5tVMAHnW6:-K5ppkuoc1l5tVMAHnW7:-1500746145) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L509)):*
That refers to the `serialize` method on the Url type in the `RefererUrl` variant. The `note` on https://fetch.spec.whatwg.org/#concept-request-referrer makes me suspect that we can assert that it's never the `client` value by this point.

---

*[src/fetch/request.rs, line 516 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pq5Ofd8Y2ArO8CkdS:-K5pq5Ofd8Y2ArO8CkdT:1113804722) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L516)):*
On the other hand, we could use the raw header api here while we're waiting: http://doc.servo.org/hyper/header/struct.Headers.html#method.set_raw

---

*[src/fetch/request.rs, line 522 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pqO6LWwy_SVpwknd8:-K5pqO6LWwy_SVpwknd9:-632031361) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L522)):*
Let's create a `global_user_agent` function that returns whatever value we want now; it will be easier to replace with the right thing when integrating later.

---

*[src/fetch/request.rs, line 532 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pt2JDlci7ZirCy7Oj:-K5pt2JDlci7ZirCy7Ok:936058154) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L532)):*
Let's make a function called modify_request_headers and consider lifting relevant portions of  http://mxr.mozilla.org/servo/source/components/net/http_loader.rs#504 .

---

*[src/fetch/request.rs, line 544 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5ptchGZQMFRxrTOdPu:-K5ptchHgA-sdmtH7mrz:-216813982) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L544)):*
We can implement this step - relative URL schemes like http/https contain data including username and password (http://doc.servo.org/servo/url/struct.RelativeSchemeData.html) which is what "include credentials" means in this step.

---

*[src/fetch/request.rs, line 552 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pxVTipX4Hw5vA5kI5:-K5pxVTipX4Hw5vA5kI6:-199849319) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L552)):*
This will need to be mutable.

---

*[src/fetch/request.rs, line 555 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pxHwrYT7C3tNlasnW:-K5pxHwrYT7C3tNlasnX:1121359643) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L555)):*
Let's have a `let complete_http_response_from_cache = None;` and use that in the following `if`.

---

*[src/fetch/request.rs, line 564 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pxeOrRWgthgb7L5B3:-K5pxeOrRWgthgb7L5B4:-677731829) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L564)):*
Let's make a `response_needs_revalidation(response: &Response) -> bool` function to encapsulate this check (it can just return false for now).

---

*[src/fetch/request.rs, line 568 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pxynLzXP1RrtjwZtS:-K5pxynLzXP1RrtjwZtT:1588796938) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L568)):*
Let's create this.

---

*[src/fetch/request.rs, line 573 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5py7B5n__fALg1uMDL:-K5py7B5n__fALg1uMDM:1534501283) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L573)):*
We can use the result of the earlier check (or at least the same function)

---

*[src/fetch/request.rs, line 586 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5py_phBWIl577UpC3s:-K5py_phBWIl577UpC3t:641167590) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L586)):*
`response.is_none()` is more idiomatic.

---

*[src/fetch/request.rs, line 592 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pyxcxZY2LLWo1uzoA:-K5pyxcxZY2LLWo1uzoB:1535696275) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L592)):*
We'll probably want parentheses here to ensure proper order of operations.

---

*[src/fetch/request.rs, line 600 \[r1\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K5pz3q8ob9tZYtkGH46:-K5pz3q8ob9tZYtkGH47:677251170) ([raw file](https://github.com/jdm/fetch/blob/e6458206423ca00cf4f4336dfe8a67aaa2840e77/src/fetch/request.rs#L600)):*
Yep!

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdm/fetch/2#-:-K5pzHFtZLuERZ_9Yok3:-684097406)*

**Comment by nikkisquared** [comment]
I've got my second draft now! I did my best on all but one of your suggestions. Since I'm short on time today like yesterday, I still haven't gone for compiling it to check over my Rust errors, but I'll be able to do that on at least Monday!

Thanks ahead of time for reviewing :)

**Comment by jdm** [comment]
Great! A couple small nits for clarity and this is good to merge.

---

Reviewed 2 of 2 files at r2, 3 of 3 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[src/fetch/request.rs, line 645 \[r2\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F1DdxMOu23hDrfBfb:-K6F1DdxMOu23hDrfBfc:1804288652) ([raw file](https://github.com/jdm/fetch/blob/eae8a869f2aaf0e49a5cafe47449c1abc5d8bae2/src/fetch/request.rs#L645)):*
This is equivalent to `complete_http_response_from_cache.is_some()`.

---

*[src/fetch/request.rs, line 593 \[r5\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F2s2YnSaIQAYJV5fY:-K6F2s2YnSaIQAYJV5fZ:-1402066240) ([raw file](https://github.com/jdm/fetch/blob/109b9d5a64f12fc77c8f08980c437608a0383d43/src/fetch/request.rs#L593)):*
Let's be explicit here and use Referer::Client, since we'll get a build error if we ever add any more variants to Referer without updating this.

---

*[src/fetch/request.rs, line 602 \[r5\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F36BOuIvmayBxnwcQ:-K6F36BOuIvmayBxnwcR:911347232) ([raw file](https://github.com/jdm/fetch/blob/109b9d5a64f12fc77c8f08980c437608a0383d43/src/fetch/request.rs#L602)):*
_origin will avoid a warning about an unused variable here.

---

*[src/fetch/request.rs, line 627 \[r5\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F3EAMOOh1YYueKixy:-K6F3EAMOOh1YYueKixz:1935453324) ([raw file](https://github.com/jdm/fetch/blob/109b9d5a64f12fc77c8f08980c437608a0383d43/src/fetch/request.rs#L627)):*
The `: Option<Basic>` probably isn't necessary any more with the subsequent changes.

---

*[src/fetch/request.rs, line 795 \[r5\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F45gvR2UZIURkU-eK:-K6F45gw8vneU15TMVKq:-19581946) ([raw file](https://github.com/jdm/fetch/blob/109b9d5a64f12fc77c8f08980c437608a0383d43/src/fetch/request.rs#L795)):*
`if url.password().is_some() {`

---

*[src/fetch/request.rs, line 489 \[r6\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F4dwK_p0PYopQLkcj:-K6F4dwK_p0PYopQLkck:1802971142) ([raw file](https://github.com/jdm/fetch/blob/9b28a65b2d7f72dcb79854724718a03b39b550c1/src/fetch/request.rs#L489)):*
I don't think this clone is necessary, since `request` can't be used after this point.

---

*[src/fetch/request.rs, line 513 \[r6\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F4hPcOcDpUjO4mjoA:-K6F4hPdUmcWonDLQ55Q:523053066) ([raw file](https://github.com/jdm/fetch/blob/9b28a65b2d7f72dcb79854724718a03b39b550c1/src/fetch/request.rs#L513)):*
I don't think this clone is necessary.

---

*[src/fetch/request.rs, line 529 \[r6\]](https://reviewable.io:443/reviews/jdm/fetch/2#-K6F4mY-KzeWUPaYszwB:-K6F4mY-KzeWUPaYszwC:1016086478) ([raw file](https://github.com/jdm/fetch/blob/9b28a65b2d7f72dcb79854724718a03b39b550c1/src/fetch/request.rs#L529)):*
Unnecessary?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdm/fetch/2#-:-K6F52qvZ8wBcLACZllO:-629684661)*

**Comment by jdm** [comment]
Reviewed 3 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/jdm/fetch/2)*

**Pull request merged**
